### ISSUE TITLE
stale metrics exported

### ISSUE THREAD

**Issue by jan--f** [digitalocean/ceph_exporter#102]
Metrics that carry pool names or daemon IDs as a labels stay after the respective entity has been deleted from the cluster.
To reproduce, create a pool until the ceph_exporter exports it, then delete it. The exporter will keep exporting the last pool metrics for said pool until restarted.

**Comment by neurodrone** [comment]
Long-term we should just move these to const metrics rather than using gauges for those. That way once the collection stops prometheus should automatically discard the timeseries.

Let's keep this issue open until then.

**Comment by alram** [comment]
Closing since a fix for this was merged
