### ISSUE TITLE
Cannot connect to ceph cluster

### ISSUE THREAD

**Issue by charlieuk2k** [digitalocean/ceph_exporter#106]
When running `docker run -v /etc/ceph:/etc/ceph --net=host -it digitalocean/ceph_exporter` I get the following error:

`cannot connect to ceph cluster: rados: No such file or directory`

Am I doing something wrong?

**Comment by de1m** [comment]
I've the same issue, my problem was, that the ceph.conf or keyring was not readible

**Comment by charlieuk2k** [comment]
> I've the same issue, my problem was, that the ceph.conf or keyring was not readible

I decided to just use the built in ceph exporter.

**Comment by fat8701** [comment]
I've the same issue, because i use other ceph.user rather than default ceph.user admin，you need to add https://github.com/digitalocean/ceph_exporter/blob/luminous/exporter.yml in /etc/ceph and modify the right user in this yaml file.

**Comment by yawenli2023** [comment]
> > I've the same issue, my problem was, that the ceph.conf or keyring was not readible
> 
> I decided to just use the built in ceph exporter.

How to use built-in ceph exporter? is it in Prometheus helm chart?
