### ISSUE TITLE
ceph_exporter need to installed on each node ?

### ISSUE THREAD

**Issue by Alexvianet** [digitalocean/ceph_exporter#109]
ceph_exporter need to installed on each node? or it's enough installed ceph_exporter on one node?

**Comment by imluyuan** [comment]
use ceph.conf and export.yaml on one node

./ceph_exporter -ceph.config="/etc/nova/" -exporter.config="exporter.yml"
2018/11/29 23:32:37 Starting ceph exporter for cluster: xxxx-rg1
2018/11/29 23:32:37 Starting ceph exporter for cluster: xxxx-rg2
2018/11/29 23:32:37 Starting ceph exporter on ":9128"

**Comment by alram** [comment]
Only one node as mention in the previous comment. Closing.
