### ISSUE TITLE
Will ceph mimic be supported soon?

### ISSUE THREAD

**Issue by yanchicago** [digitalocean/ceph_exporter#111]
The latest version shows supporting luminous. Will it work for ceph v13.2.2?

**Comment by neurodrone** [comment]
We have planned to switch to mimic at some point early this year but might not be in this month. Meanwhile if you intend to make mimic-related changes feel free to make a PR and I will create a mimic branch we can merge it into.

**Comment by mnaser** [comment]
FYI, mimic exposes prometheus metrics directly

**Comment by alram** [comment]
Mimic was never supported, we skipped from Luminous to Nautilus since Mimic was never LTS.
