### ISSUE TITLE
Collect Metrics using Ceph Exporter without exposing it on port

### ISSUE THREAD

**Issue by johnwalker511** [digitalocean/ceph_exporter#115]
I want to just collect metrics using Ceph Exporter Methodology and use those values for other purpose but I do not want to expose it on localhost:9128. How it can be done using Ceph Exporter Functions or Methods defined here as dependency in other project.

**Comment by sosodev** [comment]
Ceph exporter hasn't been designed for this use case. You'd be better of directly utilizing [go-ceph](https://github.com/ceph/go-ceph) and using our code as a reference for whatever it is you might want to accomplish.
