### ISSUE TITLE
OSD Latency are not correctly collected in Nautilus

### ISSUE THREAD

**Issue by yoshikado** [digitalocean/ceph_exporter#136]
In Nautilus the structure of the output of ceph osd perf has changed a little bit, and therefore it looks like collecting OSD latency metrics is failing.
The following two metrics are not collected.
- commit_latency_ms
- apply_latency_ms

As far as I have seen from the commit log, there was a fix for this but got reverted somehow.
https://github.com/digitalocean/ceph_exporter/commit/1f2df8db38b2a400758ef37ed2a531965ee120fe#diff-1536b81b5897f95267830a7c215ad5ab

**Comment by alram** [comment]
Thanks for the report. It should be fixed now

**Comment by homer314** [comment]
Hi guys, and what about adding ceph_osd_op_*_latency counter?
It would be really usefull to have those metrics too

**Comment by baergj** [comment]
@homer314 Please open a new issue for any feature requests. Thanks! Also, we're always happy to take patches. :)
