### ISSUE TITLE
Support for Jewel?

### ISSUE THREAD

**Issue by byxorna** [digitalocean/ceph_exporter#15]
I see some complaints when querying `/metrics` when connected to a ceph jewel cluster:
```
2016/05/17 16:40:01 failed collecting cluster recovery/client io: can't parse units "op"
```

It is probably balking at this line in the `ceph -s` output: `client io 20166 kB/s wr, 0 op/s rd, 42 op/s wr`. Older versions only reported op/s, but jewel reports ops read and ops write.

**Comment by nickvanw** [comment]
Greetings @byxorna! 

Thanks for the report - we should be able to put out a fix for this very soon! I'll leave this issue open until the PR is in.

**Comment by byxorna** [comment]
@nickvanw awesome, thanks for your prompt response!

**Comment by byxorna** [comment]
@neurodrone @nickvanw seems to still be a problem, after building with 8af54c15932df3a6f210ca8d7294dfe7d1139cf8. 

```
2016/05/17 21:17:03 failed collecting cluster recovery/client io: can't parse units "op"
2016/05/17 21:17:03 failed collecting cluster recovery/client io: can't parse units "op"
2016/05/17 21:17:06 failed collecting cluster recovery/client io: can't parse units "op"
2016/05/17 21:17:06 failed collecting cluster recovery/client io: can't parse units "op"
```
