### ISSUE TITLE
ceph_health_status_interp's status

### ISSUE THREAD

**Issue by zhaowenliang521** [digitalocean/ceph_exporter#160]
ceph_health_status_interp
# HELP ceph_health_status_interp Health status of Cluster, can vary only between 4 states (err:3, critical_warn:2, soft_warn:1, ok:0)

with the source code ,i do not find soft_warn define,does ceph_health_status_interp useful for ceph monitoring?
can someone explain this metric?thank you

**Comment by alram** [comment]
Can you point me to the ceph doc/code about this? I remember some discussion about adding a 4th health status in Ceph but cannot find any reference to it.

**Comment by alram** [comment]
A colleague pointed out that it's in our code base, sorry about that. The definition for what status trigger what health state is available here: https://github.com/digitalocean/ceph_exporter/blob/luminous/collectors/health.go#L272-L345
