### ISSUE TITLE
can not build 

### ISSUE THREAD

**Issue by jacobluo** [digitalocean/ceph_exporter#168]
[root@VM_0_13_centos ceph_exporter]# go install
# github.com/digitalocean/ceph_exporter/vendor/github.com/ceph/go-ceph/rados
vendor/github.com/ceph/go-ceph/rados/ioctx.go:453:2: could not determine kind of name for C.rados_read_op_omap_get_vals2

[root@VM_0_13_centos ceph_exporter]# rpm -qa |grep rbd
librbd1-10.2.5-4.el7.x86_64
librbd1-devel-10.2.5-4.el7.x86_64

[root@VM_0_13_centos ceph_exporter]# rpm -qa |grep rados
librados2-devel-10.2.5-4.el7.x86_64
librados2-10.2.5-4.el7.x86_64

**Comment by neurodrone** [comment]
@jacobluo 👋 did this get fixed for you?
