### ISSUE TITLE
ceph_exporter gather error

### ISSUE THREAD

**Issue by jeffaryhe** [digitalocean/ceph_exporter#186]
ceph nautilus；I stopped a  osd service。ceph_exporter The following error occurs，So Prometheus couldn't collect it
This error reporting problem needs to be resolved

An error has occurred while serving metrics:

collected metric "ceph_osd_down" { label:<name:"cluster" value:"ceph" > label:<name:"device_class" value:"hdd" > label:<name:"host" value:"ceph1" > label:<name:"osd" value:"osd.2" > label:<name:"rack" value:"default" > label:<name:"root" value:"" > label:<name:"status" value:"down" > gauge:<value:1 > } was collected before with the same name and label values

**Comment by 281889448** [comment]
Ceph OSd crush Link OSD caused this problem ，Value failure caused by repeated occurrences

**Comment by neurodrone** [comment]
Can you paste the output of `ceph osd tree`?

**Comment by sosodev** [comment]
Closing this in favor of #99 which better describes the bug
