### ISSUE TITLE
compile get error: "could not determine kind of name for C.rados_mgr_command"

### ISSUE THREAD

**Issue by kazu12** [digitalocean/ceph_exporter#214]
I use go version 1.18, and compile in centos  7.9.2009. I get error:

`# github.com/ceph/go-ceph/rados
/root/go/pkg/mod/github.com/ceph/go-ceph@v0.14.0/rados/command.go:106:9: could not determine kind of name for C.rados_mgr_command
`
I also changed tag "luminous", "mimic", "nautilus", and "octopus",  it is still not working.

how can I resovle this problem?

**Comment by sosodev** [comment]
Do you have the libs for the CGO dependencies? https://github.com/ceph/go-ceph#installation

**Comment by kazu12** [comment]
yes, before I compiled , I have already installed  librados2-devel, librb1-devel. I can't find there is some package like libcephfs**-devel. 
after I installed centos-release-ceph-nautilu, it still no work.
btw, my OS is centos, 7.9.2009. Is the system's problem?

**Comment by kazu12** [comment]
it solved. I use the tag nautilu, and compiled ok.

thinks!
