### ISSUE TITLE
Feature Request: Scrub/Deepscru/slow request counts

### ISSUE THREAD

**Issue by magicrobotmonkey** [digitalocean/ceph_exporter#22]
Would it be possible to export counts for scrub, deepscrub, blocked requests, osds with blocked requests? These metrics are very useful to graph against latency and i/o bandwidth for evaluating cluster performance.

**Comment by magicrobotmonkey** [comment]
I'm on vacation next week and may take a stab at adding this, it looks pretty straightforward.

**Comment by mdlayher** [comment]
Please do!  We'd be happy to accept the contribution.  @neurodrone , does that work for you too?

**Comment by neurodrone** [comment]
That'd indeed be helpful! What command do you intend on using to get those values out?

**Comment by mdlayher** [comment]
Hey @magicrobotmonkey , have you had any luck working on this?

**Comment by magicrobotmonkey** [comment]
No haven't had the free time. I have a 6 hour flight thursday though, if i can get a dev env going i may take a whack at it.

**Comment by craig08** [comment]
I get the scrubbing information from `pgmap` of `ceph status -f json`. Although the scrubbing state of PG I have ever seen is always `active+clean+scrubbing`, I don't really know if there exist other states combined with scrubbing, like `active+degraded+scrubbing`? Therefore I just summed all possible numbers up.

**Comment by magicrobotmonkey** [comment]
Awesome, thanks so much! I'll test it asap!
