### ISSUE TITLE
fatal error: rados/librados.h: No such file or directory

### ISSUE THREAD

**Issue by yxiaoy6** [digitalocean/ceph_exporter#228]
go install -tags quincy

github.com/ceph/go-ceph/rados
../go/pkg/mod/github.com/ceph/go-ceph@v0.14.0/rados/command.go:5:11: fatal error: rados/librados.h: No such file or directory
    5 | // #include <rados/librados.h>
      |           ^~~~~~~~~~~~~~~~~~
compilation terminated.

**Comment by alram** [comment]
You're missing the header file, it's provided by the `librados-dev` or `librados-devel` package depending on your distribution
