### ISSUE TITLE
Add Docs Listing the Exported Metrics

### ISSUE THREAD

**Issue by dror1212** [digitalocean/ceph_exporter#229]
I am not sure if I am missing it, but I can't find any documentation regarding the metrics that are being provided by the exporter. It could be useful to understand what the tool give and what use-case it fits.

**Comment by alram** [comment]
That's a great idea. It might take a while for us to get to it tho since there are a lot of them!

**Comment by baergj** [comment]
@alram FWIW, there are docs for the metrics in the code (they get defined alongside the metrics); if I understand the request correctly, it's that we somehow get those into a readable form without folks having to read the the code or launch the exporter.

I wonder if there's some way to scrape the docs out of the exporter and process them?

**Comment by alram** [comment]
Mh yeah that sounds like the fastest approach. I can have a quick look at that tomorrow

**Comment by dror1212** [comment]
Just wanted to say that I am appreciating it!
