### ISSUE TITLE
Build Public Container

### ISSUE THREAD

**Issue by chaosaffe** [digitalocean/ceph_exporter#27]
On OSX the Ceph packages are not available to build the binary and create a container. We use Ceph in our production systems, but installing golang on the nodes to build the package is something to be avoided.

This could be mitigated by using a CI system (Travis?) to do the builds and create a public container for the exporter (which is somewhat implied by the tag `digitalocean/ceph_exporter` used to build the image)

**Comment by mdlayher** [comment]
Seems reasonable to me!  We just did the same with https://github.com/digitalocean/netbox.

**Comment by neurodrone** [comment]
I like the idea of having a public container on dockerhub etc. and pushing to it on success via Travis since we already integrate into it.

@thecanadianbaker, is this something that you will be interested in working on?

**Comment by thecanadianbaker** [comment]
I would be happy to. I will try to get on a PR this weekend

**Comment by NegatioN** [comment]
Did this ever come closer to fruition? :) We would also be interested in having a public container, instead of maintaining our separate fork.

**Comment by chaosaffe** [comment]
@NegatioN no, I never got around to it. I am not using Ceph at the new company, and haven't had the chance to come back to it on my personal time. My apologies

**Comment by neurodrone** [comment]
The public container should now be available at `digitalocean/ceph_exporter`.
