### ISSUE TITLE
Failing to collect IO and health metrics

### ISSUE THREAD

**Issue by cristicalin** [digitalocean/ceph_exporter#28]
When connected to a Firefly cluster the IO and health collectors fail to parse. Here is an extract of the exporter output.

```
2016/08/31 11:32:11 Starting ceph exporter on ":9128"
2016/08/31 11:32:17 [ERROR] cannot extract total bytes: strconv.ParseFloat: parsing "": invalid syntax
2016/08/31 11:32:17 [ERROR] cannot extract used bytes: strconv.ParseFloat: parsing "": invalid syntax
2016/08/31 11:32:17 [ERROR] cannot extract available bytes: strconv.ParseFloat: parsing "": invalid syntax
2016/08/31 11:32:17 failed collecting cluster health metrics: strconv.ParseFloat: parsing "": invalid syntax
2016/08/31 11:32:17 [ERROR] Unable to collect data from ceph osd df rados: Invalid argument
2016/08/31 11:32:17 failed collecting osd metrics: rados: Invalid argument
```

What is the version of CEPH this collector has been developed/tested on ?

**Comment by neurodrone** [comment]
We haven't tested this on Firefly since it was retired last year: http://docs.ceph.com/docs/master/releases/. Ceph exporter is currently supported to work only on the valid LTS releases, i.e. Hammer and Jewel.

I will make a note of this in the README.
