### ISSUE TITLE
latest (as of 2016-12-29) image does not work on newer Ceph cluster

### ISSUE THREAD

**Issue by apsega** [digitalocean/ceph_exporter#42]
Hey!

Just now updated our ceph-exporter to latest image (previously our image was 3 weeks old) and we've noticed that while it works with Ceph cluster version `10.2.2` it gets `connection timeouts` with newer ones i.e. `10.2.3`:
```
# docker logs -f ceph-env-region1
2016/12/29 11:06:35 cannot connect to ceph cluster: rados: Connection timed out
2016/12/29 11:11:35 cannot connect to ceph cluster: rados: Connection timed out
2016/12/29 11:16:35 cannot connect to ceph cluster: rados: Connection timed out
2016/12/29 11:21:35 cannot connect to ceph cluster: rados: Connection timed out
2016/12/29 11:26:36 cannot connect to ceph cluster: rados: Connection timed out
2016/12/29 11:31:36 cannot connect to ceph cluster: rados: Connection timed out
```
Have you tried it with newer version than `10.2.2 `? Also it would be cool if you would tag any exporter releases, so we won't have any headaches reverting back :)

**Comment by mdlayher** [comment]
Hey hey, apologies for the trouble.  I'm not the Ceph expert here (that'd be @neurodrone), but I figured I'd give you a heads-up: most of the company is out this week.  I imagine that somebody would be able to look into this more on Monday if nothing else. Apologies for the trouble.

We have some scripts in place in our netbox repo that enable pushing docker images with git tags, so we could probably tag a release once this is resolved.
