### ISSUE TITLE
Exporter displays `0` values for ceph_osd_up even if OSD has been removed from cluster

### ISSUE THREAD

**Issue by apsega** [digitalocean/ceph_exporter#47]
We've noticed the issue with ceph_exporter that it still displays `ceph_osd_up` metric with value (0), even if that OSD has been removed from Cluster.

Does the exporter have counter resets or something like that?

We're using Docker container with ceph_exporter version 0.1.0.

Thanks!

**Comment by mdlayher** [comment]
If I had to guess, it's probably because this exporter isn't using "const metrics", which are generated on the fly using predefined descriptions.  My understanding is that this is the correct approach for custom exporters.

**Comment by apsega** [comment]
OK. It seems that those counters reset after a ~ day 👍
