### ISSUE TITLE
Wrong utilization and variance when OSD is out

### ISSUE THREAD

**Issue by craig08** [digitalocean/ceph_exporter#48]
When one of the OSDs is out, `ceph osd df -f json` displays -nan for utilization and variance.
Like following:
```
        {
            "id": 4,
            "name": "osd.4",
            "type": "osd",
            "type_id": 0,
            "crush_weight": 0.047791,
            "depth": 2,
            "reweight": 0.000000,
            "kb": 0,
            "kb_used": 0,
            "kb_avail": 0,
            "utilization": -nan,
            "var": -nan,
            "pgs": 50
        }
```

And the exporter says
```
2017/04/10 19:51:07 Starting ceph exporter on ":9128"
2017/04/10 19:51:08 failed collecting osd metrics: invalid character 'n' in numeric literal
```

The `ceph_osd_average_utilization` variable also gets wrong in this case.

**Comment by neurodrone** [comment]
Interesting. Which version of Ceph are you running?

**Comment by craig08** [comment]
Ceph Jewel 10.2.5

**Comment by neurodrone** [comment]
Thanks! I will look at pushing out a fix for this soon.

**Comment by craig08** [comment]
The value `-nan` is hard to unmarshal because it is neither a valid number nor a valid double quoted string.
Due to golang does not support [unmarshal nan and inf number in json](https://github.com/golang/go/issues/3480), I came up with a dumb solution to replace all `-nan` in the response of `MonCommand` to `0`.

`buf = bytes.Replace(buf, []byte(":-nan"), []byte(":0"), -1)`

And it seems to work. Do you have any other tidy solution or should I send a pull request to you?

**Comment by neurodrone** [comment]
Oh sure, feel free to send a PR up! At the rate of things I have scheduled, it looks like I will be able to get to this earliest by Friday.

**Comment by neurodrone** [comment]
There's a tracker for making sure the invalid json gets addressed: http://tracker.ceph.com/issues/18239 but there has been no movement on that yet. It's weird to make the change to replace that specific string in a JSON output, but a hacky solution will at least get this working until the fix goes out.

**Comment by craig08** [comment]
I just sent a pull request to make a workaround by this method. Feel free to reject or amend the commit.
Thank you very much.
