### ISSUE TITLE
Works with Grafana?

### ISSUE THREAD

**Issue by skloeckner** [digitalocean/ceph_exporter#50]
Hello there,

I am trying to use the docker image to have Grafana scrape the data from it and use the ceph dashboard here:

https://grafana.com/dashboards/917

However, I believe the docker image is missing the main prometheus server. I am wondering if Grafana is supported out of the box with this as a data source?

Or

Do I need to setup a full prometheus server to perform scrapes?

The reason I ask is because when going to http://$dockerhostIP:9128/metrics the metrics are clearly available.

**Comment by skloeckner** [comment]
Did some more searching and I see that @apsega also uses the dashboard.

Would you care to elaborate on your setup?

My goal is to keep my setup as minimal as possible.

I would be glad to do a quick write-up on how to set this up using Grafana.

**Comment by apsega** [comment]
Hey,

Exporters are always separate from Prometheus server, so you'll have to run another container with Prometheus to scrape exporter, then feed the it to Grafana as a data source.

**Comment by skloeckner** [comment]
Awesome. Thanks for letting me know. I will setup a separate prometheus docker container.
