### ISSUE TITLE
 jewel -> luminous ceph_health_status value to 1 will not change ?

### ISSUE THREAD

**Issue by SwarmKit** [digitalocean/ceph_exporter#65]
jewel -> luminous ceph_health_status value to 1 will not change ?

**Comment by calvinmorrow** [comment]
I've had 2 separate clusters upgraded from Jewel to Luminous (and updated ceph_exporter with Luminous libs) that both exhibit this issue.  Ceph health / status shows HEALTH_OK, ceph_exporter reports:
```
# HELP ceph_health_status Health status of Cluster, can vary only between 3 states (err:2, warn:1, ok:0)
# TYPE ceph_health_status gauge
ceph_health_status{cluster="ceph"} 1
```

I've tried changing `mon_health_preluminous_compat=true` however ceph_health_status stays at 1.

**Comment by PAStheLoD** [comment]
We're experiencing the same issue. (Tried with a fresh build and with using the latest docker image: https://hub.docker.com/r/digitalocean/ceph_exporter/tags/ , which is 8 months old.)

This is of course really confusing, considering that it's unlikely to be an off-by-one error, as the health collector explicitly [matches HEALTH_OK](https://github.com/digitalocean/ceph_exporter/blob/master/collectors/health.go#L167) or [signals an error by returning 2](https://github.com/digitalocean/ceph_exporter/blob/master/collectors/health.go#L529).

**Comment by PAStheLoD** [comment]
Digging further (deeper into the dark) it turns out that mon_health_preluminous_compat=true has no effect, Ceph monitors still send the `"overall_status": "HEALTH_WARN"` data.

Of course there's a [fork](https://github.com/shoghicp/ceph_exporter/commit/ec2a69243659c38746167191db881988d95168b6) with only one commit that solves it.

**Comment by sosodev** [comment]
This was fixed https://github.com/digitalocean/ceph_exporter/commit/9c40ffc6209ba30a45c1efb3c590f5f1c04f0c71
