### ISSUE TITLE
Luminous compatibillity

### ISSUE THREAD

**Issue by skunkr** [digitalocean/ceph_exporter#78]
Hi,
Any new regarding Luminous full compatibillity ?

**Comment by uncelvel** [comment]
Maybe it's not compatibility bro. This document have written

> Ceph exporter is tested only on Ceph's Hammer(v0.94) and Jewel(v10.2) releases. It might not work as expected with older or non-LTS versions of Ceph.

**Comment by goldyfruit** [comment]
What about using Ceph Manager to collect the data with Luminous ?
`# ceph mgr module enable prometheus`

**Comment by neurodrone** [comment]
Please see https://github.com/digitalocean/ceph_exporter/tree/luminous for compatibility with Luminous.
