### ISSUE TITLE
can ceph_exporter support getting rbd info?

### ISSUE THREAD

**Issue by fffffreedom** [digitalocean/ceph_exporter#81]
hi

i want to get rbd image info using ceph_exporter, but after reading the source code, i found it not support.
and there is a question confused me:
as you know, the command we used to get info of rbd is started with"rbd", while in ceph_exporter code, it seems the command are started with "ceph"?
func (o *OSDCollector) cephOSDDFCommand() []byte {
	cmd, err := json.Marshal(map[string]interface{}{
		"prefix": "osd df",
		"format": "json",
	})
	if err != nil {
		panic(err)
	}
	return cmd
}

**Comment by cristicalin** [comment]
`ceph_exporter` uses the go-ceph (https://github.com/ceph/go-ceph) library which does have an rbd client.
Looking at the code (https://github.com/ceph/go-ceph/blob/master/rbd/rbd.go#L297-L317) it seems that there is a `Stat()` function that provides a size, an object size and a number of objects.
Are these metrics actually relevant?

**Comment by fffffreedom** [comment]
@cristicalin 
we want to monitor the used size of an image,  so as to resize the images if the available size is not enough.
the code is not right for us, but thank you all the same

**Comment by tonobo** [comment]
@fffffreedom @cristicalin I'm currently working on usage tracking by using `rbd_diff_iterate2`. But I would suggest to add a seperated metrics path e.g `/rbdmetrics` to specify a lower scrape ratio. Next day's i'll open a pull request for go-ceph.

**Comment by sosodev** [comment]
As mentioned above this doesn't really fit ceph exporter but is better suited for custom tooling using go-ceph.
