### ISSUE TITLE
jewel not collect monitor data

### ISSUE THREAD

**Issue by proffust** [digitalocean/ceph_exporter#96]
Hello!
`root@ceph-osd-mon02:~# ceph --version
`
`
ceph version 10.2.10 (5dc1e4c05cb68dbf62ae6fce3f0700e4654fdbbe)
`
Using exporter in docker image
`docker run -v /etc/ceph:/etc/ceph -d --net=host digitalocean/ceph_exporter`
OSD metrics collect normal, but no monitor metrics. In logs :
`root@ceph-osd-mon02:~# docker logs -f a70ac49a79d3
`
`
2018/07/19 16:29:19 Starting ceph exporter on ":9128"
`
`
2018/07/19 16:29:29 failed collecting monitor metrics: rados: Invalid argument
`
`
2018/07/19 16:41:56 failed collecting monitor metrics: rados: Invalid argument`

ceph.conf - https://pastebin.com/sYPgqPSR

**Comment by yanbumo** [comment]
metoo

**Comment by Francesko90** [comment]
I solved this problem using correct version of software, maybe it's same problem

https://github.com/digitalocean/ceph_exporter/releases/tag/2.0.0-jewel

**Comment by imluyuan** [comment]
me too

**Comment by imluyuan** [comment]
monitors: add back clock skew and latency metric support

**Comment by imluyuan** [comment]
I use ceph 0.94-version form production.
1.

**Comment by imluyuan** [comment]
commit 6f290751c9318590837b0056eaaff876706b726f
Author: Vaibhav Bhembre <vaibhav@digitalocean.com>
Date:   Sat Jun 23 18:51:06 2018 -0400

**Comment by imluyuan** [comment]
**commit 6f290751c9318590837b0056eaaff876706b726f**
Author: Vaibhav Bhembre <vaibhav@digitalocean.com>
Date:   Sat Jun 23 18:51:06 2018 -0400

1.Remove this commit form monitor.go  If u use ceph version of 0.94 and 10.2.10.This commit only Support L +version.
2.go build again
3.

**Comment by AlexZzz** [comment]
Same problem with 10.2.11 cluster.

**Comment by sosodev** [comment]
As mentioned above this seems to have been caused by using the incorrect version of ceph exporter for the cluster. https://github.com/digitalocean/ceph_exporter/issues/96#issuecomment-415338832

We'll soon have support for Nautilus, Octopus, and Pacific clusters with a single version of ceph exporter.
