### ISSUE TITLE
Missing Misplaced Objects

### ISSUE THREAD

**Issue by pryorda** [digitalocean/ceph_exporter#98]
Both ceph_misplaced_objects and degraded_objects of these show 0, but my ceph -s output looks like.

  data:
    pools:   3 pools, 364 pgs
    objects: 1103M objects, 21756 GB
    usage:   47129 GB used, 26597 GB / 73727 GB avail
    pgs:     64413611/2314108426 objects degraded (2.784%)
             466174533/2314108426 objects misplaced (20.145%)
             237 active+clean
             106 active+remapped+backfill_wait
             15  active+undersized+degraded+remapped+backfill_wait
             5   active+undersized+degraded+remapped+backfilling
             1   active+remapped+backfilling

Is this normal?

**Comment by FATruden** [comment]
I have same problem. i use ceph 12.2.5.
Maybe it's fix: https://github.com/digitalocean/ceph_exporter/pull/85

**Comment by alram** [comment]
added a while back. Closing the issue.
